language: c

dist: trusty
sudo: required

# https://docs.travis-ci.com/user/languages/c/
#addons:
#  apt:
#    sources:
#      - ubuntu-toolchain-r-test
#    packages:
#      - g++-8
#env: MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

before_install: 
  - sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
  - sudo apt-get -y update

install: 
  - sudo apt-get install -y wget
  - sudo apt-get install -y build-essential software-properties-common
  - sudo apt-get install -y libtool autoconf automake
  - sudo apt-get install -y libssl-dev libcurl4-openssl-dev libperl-dev
  - sudo apt-get install -y zlib1g-dev libbz2-dev libreadline-dev
  - sudo apt-get install -y cmake clang golang
  - sudo apt-get install -y gcc-snapshot
  - sudo apt-get install -y gcc-8 g++-8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-8
  - sudo update-alternatives --config gcc
  - sudo gcc -v

before_script: 
  - wget https://raw.githubusercontent.com/Minaminx/Component/master/dependence/pcre-8.42.tar.gz && tar -zxf pcre-8.42.tar.gz
  - git clone --depth=1 https://github.com/nanqinlang-fork-web-nginx/zlib-cloudflare.git
  - git clone --depth=1 --branch=master https://github.com/Minaminx/Core.git nginx
  - git clone --depth=1 --branch=master https://github.com/Minaminx/BoringSSL.git boringssl
  - chmod -R +x pcre-8.42 zlib-cloudflare nginx boringssl

script: 
  - cd pcre-8.42 && ./configure --enable-pcregrep-libz --enable-pcregrep-libbz2 --enable-pcretest-libreadline --enable-utf8 --enable-unicode-properties --enable-pcre16 --enable-pcre32 --enable-jit && cd ..
  - cd zlib-cloudflare && ./configure && cd ..
  - cd boringssl && mkdir build && cd build && export CFLAGS="-Wno-error" && cmake -DCMAKE_BUILD_TYPE=Release -DOPENSSL_SMALL=1 ../ && make && cd .. && mkdir -p .openssl/lib && cd .openssl && ln -s ../include . && cd .. && cp build/crypto/libcrypto.a build/ssl/libssl.a .openssl/lib
  - cd ..
  - cd nginx && export rootdir="/home/travis/build/Minaminx/Core" && ./configure --builddir=$rootdir/nginx/travis/builder --prefix=$rootdir/nginx/travis/installer --with-http_ssl_module --with-http_v2_spdy_module --with-http_v2_module --with-http_v2_hpack_enc_module --with-pcre=$rootdir/pcre-8.42 --with-pcre-jit --with-zlib=$rootdir/zlib-cloudflare --with-boringssl-on --with-boringssl-dir=$rootdir/boringssl --with-boringssl-tls-min=TLS1_2_VERSION --with-boringssl-tls-max=TLS1_5_VERSION && touch $rootdir/boringssl/.openssl/include/openssl/ssl.h && sudo make && sudo make install

after_success: 
  - sudo $rootdir/nginx/travis/installer/sbin/nginx -V
