language: c

dist: trusty
sudo: required

# https://docs.travis-ci.com/user/languages/c/
#addons:
#  apt:
#    sources:
#      - ubuntu-toolchain-r-test
#    packages:
#      - g++-8
#env: MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

before_install: 
  - sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
  - sudo apt-get -y update

install: 
  - sudo apt-get install -y build-essential software-properties-common
  - sudo apt-get install -y gcc-snapshot
  - sudo apt-get install -y gcc-8 g++-8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-8
  - sudo update-alternatives --config gcc
  - sudo gcc -v
  - sudo apt-get install -y wget openssl libssl-dev libpcre3 libpcre3-dev zlib1g-dev
# - sudo apt-get install -y wget openssl libssl-dev

before_script: 
# - wget https://raw.githubusercontent.com/Minaminx/Component/master/dependence/pcre-8.42.tar.gz && tar -zxf pcre-8.42.tar.gz && cd pcre-8.42 && ./configure && cd ..
# - git clone --depth=1 --branch=master https://github.com/nanqinlang-fork-web-nginx/zlib-cloudflare.git && cd zlib-cloudflare && ./configure && cd ..
  - git clone --depth=1 --branch=master https://github.com/Minaminx/Core.git nginx
  - chmod -R +x nginx
  - cd nginx
  - export rootdir="/home/travis/build/Minaminx/Core"

script: 
  - ./configure --builddir=$rootdir/nginx/travis/builder --prefix=$rootdir/nginx/travis/installer --with-http_realip_module --with-http_stub_status_module --with-http_degradation_module --with-debug --with-file-aio --with-threads --without-http_fastcgi_module --without-http_uwsgi_module --without-http_scgi_module --without-http_autoindex_module --without-http_empty_gif_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_addition_module --with-http_secure_link_module --with-http_auth_request_module --with-http_slice_module --with-http_random_index_module --with-http_ssl_module --with-http_ssl_openssl_chacha_preferred_module --with-http_ssl_boringssl_tls_version_min_module --with-http_ssl_boringssl_tls_version_max_module --with-http_v2_spdy_module --with-http_v2_module --with-http_v2_hpack_enc_module --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-stream_realip_module --with-http_gzip_static_module --with-http_gunzip_module --with-http_sub_module
  - sudo make
  - sudo make install

after_success: 
  - sudo $rootdir/nginx/travis/installer/sbin/nginx -V
